### ISSUE TITLE
cygpath not found / Unable to update checked out version

### ISSUE THREAD

**Issue by helgi** [lrills/helm-unittest#18] opened 2018-03-17 21:09 UTC
`~/.helm/plugins/helm-unittest/install-binary.sh: line 14: type: cygpath: not found` shows up during installation on macOS. Does not fail the installation tho.

I had to pass in --version 0.1.1 to get the install working, without it I got the following (i can open up a separate ticket):

```
helm plugin install https://github.com/lrills/helm-unittest
Error: Unable to update checked out version
```

**Comment by lrills** [comment] 2018-03-19 08:46
Hi, helgi. `cygpath: not found` comes from [this line](https://github.com/lrills/helm-unittest/blob/master/install-binary.sh#L14) does not actually fail the scripts, I'll fix the logging next patch. 
`Error: Unable to update checked out version` seems not to be a problem of the install scripts but from helm. But I couldn't reproduce it in my local helm, would you please provide the result of
```
helm plugin install --debug https://github.com/lrills/helm-unittest
```
for some more detail?

**Comment by helgi** [comment] 2018-03-19 15:28
```
helm plugin install --debug https://github.com/lrills/helm-unittest
[debug] updating https://github.com/lrills/helm-unittest
[debug] setting version to ""
Error: Unable to update checked out version
```

**Comment by helgi** [comment] 2018-03-19 15:28
re `cygpath` yeah I just wanted to point out it was doing a check without silencing it if it was missing, didn't break anything :)

**Comment by lrills** [comment] 2018-03-20 03:46
I think i found it! The error seems to be a helm bug and fixed in https://github.com/kubernetes/helm/pull/3571 but not yet released, so for now only thing can be done is just workaround with `--version` flag.
And thanks for report! :D

**Comment by helgi** [comment] 2018-03-20 04:12
Looks like it :) Feel free to close with a "will be fixed in 2.9".

**Comment by lrills** [comment] 2018-03-23 06:11
Let's keep this for someone after :) Please allow me edit the title a little bit.

**Comment by lrills** [comment] 2021-06-22 05:54
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).

**Closed by lrills** 2021-06-22 05:54 UTC
