### ISSUE TITLE
How to test annotations that have "/" in its path?

### ISSUE THREAD

**Issue by gcavalcante8808** [lrills/helm-unittest#95] opened 2020-01-15 13:52 UTC
Hi Folks,

I'm trying to evaluate the following tests:

```
      - equal:
          path: metadata.annotations.kubernetes.io/ingress.class
          value: merged
      - equal:
          path: metadata.annotations.merged.ingress.kubernetes.io/config
          value: merged-ingress
```
But I'm receiving the following errors:

![image](https://user-images.githubusercontent.com/640897/72439106-09a1d400-3785-11ea-8cb0-33d1cc3ecceb.png)

How can I run these tests?

Thanks in advance.

**Comment by xordspar0** [comment] 2020-02-04 21:05
The problem is the dots in the annotation key, not the slash. "kubernetes.io/ingress.class" is the name of the annotation, but unittest is breaking it up as a map called `kubernetes` that contains a map called `io/ingress` that contains a key called `class`.

I'm having the same problem with a Kubernetes label that contains a dot. I haven't found a solution yet, but if I do I'll post here.

**Comment by xordspar0** [comment] 2020-02-05 15:32
The below function is responsible for traversing the data based on the `path:` value. It's a simple state machine, and it doesn't support treating `.` differently in different contexts. If we added support for this, what would the syntax look like?

1. Put the value in quotes, e.g. `metadata.annotations."kubernetes.io/ingress.class"`
2. jq uses a syntax where you can specify fields of an object with a Javascript-like syntax of `a.["b"]`. In jq, `a.b` is just a shorthand for `a.["b]`, which means you could specify our annotation with `metadata.annotations.["kubernetes.io/ingress.class"]`.

https://github.com/lrills/helm-unittest/blob/436447d3bcc47be1ed51d66bc7a21dec7d97262e/unittest/valueutils/valueutils.go#L120-L191

**Comment by xordspar0** [comment] 2020-02-05 15:42
Oh! We already support a syntax similar to jq, I just missed it when reading the code. You can do

```
metadata.annotations.[kubernetes.io/ingress.class]
```

As far as I can tell this is not documented. I'll submit a PR to add documentation on specifying paths, including this `.[]` syntax.

**Comment by xordspar0** [comment] 2020-02-05 16:13
Sorry, I was right the first time. If you specify a key with `[]`, unittest expects a number index, not a string key. We could add support for the jq syntax though.

**Comment by quintush** [comment] 2020-04-06 11:44
@gcavalcante8808 , @xordspar0, i have added the jq syntax for escaping the dots.
Since it's not merged into this repo, you can download a version from my forked repo: https://github.com/quintush/helm-unittest/releases

**Comment by xordspar0** [comment] 2020-04-06 13:30
Thanks, nice work. I hope it gets merged into upstream, but if not I'll take a look at your fork.

**Comment by gcavalcante8808** [comment] 2020-04-06 13:31
Thank you, awesome work!

**Comment by lrills** [comment] 2021-06-22 06:18
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).

**Closed by lrills** 2021-06-22 06:18 UTC

**Comment by lucasfcnunes** [comment] 2026-05-14 23:15
Is there a real solution for this issue?

**Comment by quintush** [comment] 2026-05-16 13:59
Hello @lucasfcnunes 

Using the block ([]) notation and double quotes, there is support for special characters like /.

See [jsonpath support](https://github.com/helm-unittest/helm-unittest#yaml-jsonpath-support), for more detail.

There are also some examples like [basic](https://github.com/helm-unittest/helm-unittest/blob/main/test/data/v3/basic) that implement special character validation.

Greetings,
@quintush
